language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: hhvm
        - php: 7
    allow_failures:
        - php: hhvm
        - php: 7
    
before_install:
    - composer self-update
    
install:
    - composer install --dev --prefer-source
    
script:
    - bin/phpunit