language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: hhvm
        - php: 7
    allow_failures:
        - php: hhvm
        - php: 7
    fast_finish: true

install:
    - composer install --prefer-dist

script:
    - phpunit
